apiVersion: v1
kind: Deployment
metadata:
  name: {{ .Release.Name }} -deployment
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.image.repository }}
        image: {{ .Values.image.repository }} : {{ .Values.image.tag}}
        ports:
        - containerPort: 80